# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228b3284bc64c7c5f0b35cd8019d4e6b092fdced9e4b27fdb377b4f754852f8f50bdd89343603d6b048922df93837b8a3f339e33615c91e00442eeb8dacb340c
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>

test:
  secret_key_base: 27ead6d9a0393c8ec53929adcbe89e37c93ebd7ac73915621627e30f07598cb7cd3b611ac14c0783d16642d3c41359687ce16130bb4780c5495792449dc32f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
